#!/usr/bin/env bash
# send file to remote server
if [ $4 ]; then
	exec -o StrictHostKeyChecking=no scp -i $4 $1 $3@$2:~/
else echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
