#!/usr/bin/env bash
# install bash
# change the content of default site

sudo apt-get -y install nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo /etc/init.d/nginx restart
