#!/usr/bin/env bash
# 2x number of server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo bash -c 'sed  -i -z "s#location / {#&\n\t\tadd_header X-Served-By $HOSTNAME;#1" /etc/nginx/sites-available/default'
sudo bash -c 'service nginx restart'

